server:
  port: 9000
spring:
  datasource:
    # MySQL
    # driver-class-name: com.mysql.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/blog_db

    # PostgreSQL
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/blog_db

    username: blog_db_user
    password: blog_db_passw0rd
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true


